seeds = [1,2,3,4,5]

min_num_jigs = 2
max_num_jigs = 6

min_num_racks = 2
max_num_racks = 6

# number of racks / number of parts
min_constraint = 0.5
max_constraint = 0.2

# sum of rack sizes / sum pf part sizes
rack_space_factors = [2]
